name: Check format

- uses: actions/checkout@master
  with:
    ref: ${{ github.event.pull_request.head.sha }}
- name: PEP8 Action
  uses: quentinguidee/pep8-action@v2.0.13-dev
  with:
    arguments: '--max-line-length=120'